// ReviewerNote — LLM "manager's note" inside an AgentPanel (US-009).
//
// Source: dashboardReducer's `reviews[sessionId]`, fed by `{type:'review'}` SSE
// messages. The producer is `src/reviewer.js#review` which returns
// `{ note: string, model?: string, ts?: string }`; the wire type stays open per
// the US-007 convention so we cast locally here.
//
// Empty-state mirrors the legacy public/app.js placeholder ("the LLM provides this
// once enough activity accrues…") so the panel always reserves room for the note — no layout shift when
// the first review lands.

import type { Review } from '@/types/dashboard';

export type ReviewerNoteProps = {
  review: Review | undefined;
};

type ReviewShape = { note?: string; model?: string; ts?: string };

function fmtAgo(ts: string | undefined, nowMs: number): string {
  if (!ts) return '';
  const t = Date.parse(ts);
  if (Number.isNaN(t)) return '';
  const s = Math.max(0, Math.round((nowMs - t) / 1000));
  if (s < 60) return `${s}s ago`;
  if (s < 3600) return `${Math.round(s / 60)}m ago`;
  return `${Math.round(s / 3600)}h ago`;
}

export function ReviewerNote({ review }: ReviewerNoteProps) {
  const rv = review as ReviewShape | undefined;
  const note = rv?.note?.trim();

  if (!note) {
    return (
      <div className="flex flex-col gap-1">
        <div className="flex items-center justify-between text-[14px] uppercase tracking-wider text-muted-foreground">
          <span>Manager note</span>
          <span className="font-mono normal-case text-[14px] text-muted-foreground/80">LLM</span>
        </div>
        <p className="rounded-md border border-dashed border-border/60 bg-background/40 px-3 py-2 text-[15px] leading-relaxed text-muted-foreground">
          📋 Generated by the LLM once enough activity accrues…
        </p>
      </div>
    );
  }

  const ago = fmtAgo(rv?.ts, Date.now());

  return (
    <div className="flex flex-col gap-1">
      <div className="flex items-center justify-between text-[14px] uppercase tracking-wider text-muted-foreground">
        <span>Manager note</span>
        <span className="font-mono normal-case text-[14px] text-muted-foreground/80">
          LLM · not factual{rv?.model ? ` · ${rv.model}` : ''}
        </span>
      </div>
      <blockquote className="rounded-md border border-[var(--neon-mauve)]/35 bg-[var(--neon-mauve)]/8 px-3 py-2 text-[15px] leading-relaxed text-foreground/90">
        <span className="select-none text-[var(--neon-mauve)]">📋 </span>
        {note}
        {ago ? (
          <span className="ml-2 font-mono text-[14px] text-muted-foreground/80">{ago}</span>
        ) : null}
      </blockquote>
    </div>
  );
}
